name: Testing

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echoing
    - uses: actions/checkout@main
    - run: |
       date > text.txt
       git config user.name asdf
       git config user.email sadsafas@sadasd.com
       git add .
       git commit -m "testing"
       git push
